// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Keldron (keldron.ai)

package normalizer

import "time"

// TelemetryPoint is the canonical normalized telemetry format sent to the platform.
type TelemetryPoint struct {
	ID          string             // ULID — generated by normalizer
	AgentID     string             // From agent config
	AdapterName string             // Which adapter produced this ("dcgm", "pdu", etc.)
	Source      string             // Original hostname / device ID
	RackID      string             // Resolved from rack_mapping config
	Timestamp   time.Time          // Validated original timestamp
	ReceivedAt  time.Time          // When normalizer processed it
	Metrics     map[string]float64 // Normalized to float64 values
	Tags        map[string]string  // String metadata preserved from adapters (e.g., gpu_name, gpu_model)
}
