// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: telemetry/v1/telemetry.proto

package telemetryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AckStatus indicates the result of processing a batch.
type AckStatus int32

const (
	AckStatus_ACK_STATUS_UNSPECIFIED AckStatus = 0
	AckStatus_ACK_STATUS_OK          AckStatus = 1
	AckStatus_ACK_STATUS_PARTIAL     AckStatus = 2
	AckStatus_ACK_STATUS_ERROR       AckStatus = 3
)

// Enum value maps for AckStatus.
var (
	AckStatus_name = map[int32]string{
		0: "ACK_STATUS_UNSPECIFIED",
		1: "ACK_STATUS_OK",
		2: "ACK_STATUS_PARTIAL",
		3: "ACK_STATUS_ERROR",
	}
	AckStatus_value = map[string]int32{
		"ACK_STATUS_UNSPECIFIED": 0,
		"ACK_STATUS_OK":          1,
		"ACK_STATUS_PARTIAL":     2,
		"ACK_STATUS_ERROR":       3,
	}
)

func (x AckStatus) Enum() *AckStatus {
	p := new(AckStatus)
	*p = x
	return p
}

func (x AckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_v1_telemetry_proto_enumTypes[0].Descriptor()
}

func (AckStatus) Type() protoreflect.EnumType {
	return &file_telemetry_v1_telemetry_proto_enumTypes[0]
}

func (x AckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckStatus.Descriptor instead.
func (AckStatus) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

// TelemetryBatch is a collection of telemetry points sent by an agent.
type TelemetryBatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SequenceNumber uint64                 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	SentAtMs       int64                  `protobuf:"varint,3,opt,name=sent_at_ms,json=sentAtMs,proto3" json:"sent_at_ms,omitempty"` // Unix milliseconds
	Points         []*TelemetryPoint      `protobuf:"bytes,4,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TelemetryBatch) Reset() {
	*x = TelemetryBatch{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatch) ProtoMessage() {}

func (x *TelemetryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatch.ProtoReflect.Descriptor instead.
func (*TelemetryBatch) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TelemetryBatch) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *TelemetryBatch) GetSentAtMs() int64 {
	if x != nil {
		return x.SentAtMs
	}
	return 0
}

func (x *TelemetryBatch) GetPoints() []*TelemetryPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

// TelemetryPoint is a single normalized telemetry measurement.
type TelemetryPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ULID
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AdapterName   string                 `protobuf:"bytes,3,opt,name=adapter_name,json=adapterName,proto3" json:"adapter_name,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"` // Hostname or device ID
	RackId        string                 `protobuf:"bytes,5,opt,name=rack_id,json=rackId,proto3" json:"rack_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"` // Original timestamp as Unix milliseconds
	ReceivedAtMs  int64                  `protobuf:"varint,7,opt,name=received_at_ms,json=receivedAtMs,proto3" json:"received_at_ms,omitempty"`
	Metrics       map[string]float64     `protobuf:"bytes,8,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryPoint) Reset() {
	*x = TelemetryPoint{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPoint) ProtoMessage() {}

func (x *TelemetryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPoint.ProtoReflect.Descriptor instead.
func (*TelemetryPoint) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryPoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TelemetryPoint) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TelemetryPoint) GetAdapterName() string {
	if x != nil {
		return x.AdapterName
	}
	return ""
}

func (x *TelemetryPoint) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TelemetryPoint) GetRackId() string {
	if x != nil {
		return x.RackId
	}
	return ""
}

func (x *TelemetryPoint) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *TelemetryPoint) GetReceivedAtMs() int64 {
	if x != nil {
		return x.ReceivedAtMs
	}
	return 0
}

func (x *TelemetryPoint) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// BatchAck is the platform's acknowledgement for a received batch.
type BatchAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber uint64                 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Status         AckStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=telemetry.v1.AckStatus" json:"status,omitempty"`
	AcceptedCount  int32                  `protobuf:"varint,3,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	RejectedCount  int32                  `protobuf:"varint,4,opt,name=rejected_count,json=rejectedCount,proto3" json:"rejected_count,omitempty"`
	Message        string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchAck) Reset() {
	*x = BatchAck{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAck) ProtoMessage() {}

func (x *BatchAck) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAck.ProtoReflect.Descriptor instead.
func (*BatchAck) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *BatchAck) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *BatchAck) GetStatus() AckStatus {
	if x != nil {
		return x.Status
	}
	return AckStatus_ACK_STATUS_UNSPECIFIED
}

func (x *BatchAck) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *BatchAck) GetRejectedCount() int32 {
	if x != nil {
		return x.RejectedCount
	}
	return 0
}

func (x *BatchAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_telemetry_v1_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1ctelemetry/v1/telemetry.proto\x12\ftelemetry.v1\"\xa8\x01\n" +
	"\x0eTelemetryBatch\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x04R\x0esequenceNumber\x12\x1c\n" +
	"\n" +
	"sent_at_ms\x18\x03 \x01(\x03R\bsentAtMs\x124\n" +
	"\x06points\x18\x04 \x03(\v2\x1c.telemetry.v1.TelemetryPointR\x06points\"\xd9\x02\n" +
	"\x0eTelemetryPoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12!\n" +
	"\fadapter_name\x18\x03 \x01(\tR\vadapterName\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x17\n" +
	"\arack_id\x18\x05 \x01(\tR\x06rackId\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMs\x12$\n" +
	"\x0ereceived_at_ms\x18\a \x01(\x03R\freceivedAtMs\x12C\n" +
	"\ametrics\x18\b \x03(\v2).telemetry.v1.TelemetryPoint.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xcc\x01\n" +
	"\bBatchAck\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x04R\x0esequenceNumber\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.telemetry.v1.AckStatusR\x06status\x12%\n" +
	"\x0eaccepted_count\x18\x03 \x01(\x05R\racceptedCount\x12%\n" +
	"\x0erejected_count\x18\x04 \x01(\x05R\rrejectedCount\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage*h\n" +
	"\tAckStatus\x12\x1a\n" +
	"\x16ACK_STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACK_STATUS_OK\x10\x01\x12\x16\n" +
	"\x12ACK_STATUS_PARTIAL\x10\x02\x12\x14\n" +
	"\x10ACK_STATUS_ERROR\x10\x032[\n" +
	"\x10TelemetryService\x12G\n" +
	"\vStreamBatch\x12\x1c.telemetry.v1.TelemetryBatch\x1a\x16.telemetry.v1.BatchAck(\x010\x01BMZKgithub.com/keldron-ai/keldron-agent/internal/proto/telemetry/v1;telemetryv1b\x06proto3"

var (
	file_telemetry_v1_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_v1_telemetry_proto_rawDescData []byte
)

func file_telemetry_v1_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_v1_telemetry_proto_rawDesc), len(file_telemetry_v1_telemetry_proto_rawDesc)))
	})
	return file_telemetry_v1_telemetry_proto_rawDescData
}

var file_telemetry_v1_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_telemetry_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_telemetry_v1_telemetry_proto_goTypes = []any{
	(AckStatus)(0),         // 0: telemetry.v1.AckStatus
	(*TelemetryBatch)(nil), // 1: telemetry.v1.TelemetryBatch
	(*TelemetryPoint)(nil), // 2: telemetry.v1.TelemetryPoint
	(*BatchAck)(nil),       // 3: telemetry.v1.BatchAck
	nil,                    // 4: telemetry.v1.TelemetryPoint.MetricsEntry
}
var file_telemetry_v1_telemetry_proto_depIdxs = []int32{
	2, // 0: telemetry.v1.TelemetryBatch.points:type_name -> telemetry.v1.TelemetryPoint
	4, // 1: telemetry.v1.TelemetryPoint.metrics:type_name -> telemetry.v1.TelemetryPoint.MetricsEntry
	0, // 2: telemetry.v1.BatchAck.status:type_name -> telemetry.v1.AckStatus
	1, // 3: telemetry.v1.TelemetryService.StreamBatch:input_type -> telemetry.v1.TelemetryBatch
	3, // 4: telemetry.v1.TelemetryService.StreamBatch:output_type -> telemetry.v1.BatchAck
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_telemetry_v1_telemetry_proto_init() }
func file_telemetry_v1_telemetry_proto_init() {
	if File_telemetry_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_v1_telemetry_proto_rawDesc), len(file_telemetry_v1_telemetry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_v1_telemetry_proto_depIdxs,
		EnumInfos:         file_telemetry_v1_telemetry_proto_enumTypes,
		MessageInfos:      file_telemetry_v1_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_v1_telemetry_proto = out.File
	file_telemetry_v1_telemetry_proto_goTypes = nil
	file_telemetry_v1_telemetry_proto_depIdxs = nil
}
